### ISSUE TITLE
Pointers on how to run this on my ubuntu server VM?

### ISSUE THREAD

**Issue by kamuffelnight** [burnedikt/diasend-nightscout-bridge#16]
Thank you for creating this project!

Could you/someone give me some pointers on how to run this on my ubuntu server VM? How / where do you guys run it?

I am running my local nightscout instance via docker compose. So I thought it would be easiest, to run this next to it as stanalone service. 
I´ve messed around with npm/yarn/.. for hours but to be honest I don´t completely understand what I´m doing. So I would greatly appreciate some hints what the steps are to help me figure it out.

**Comment by burnedikt** [comment]
Given that you're running nightscout via docker compose, are you familiar with docker containers per se? If so, you can pretty easily create a docker container with this project running inside like: 

`Dockerfile`
```dockerfile
FROM node:lts-alpine

WORKDIR /usr/local/app

COPY . ./

RUN yarn install
RUN yarn build

CMD [ "node", "dist/run.js" ]
```

You can then build the image like `docker build .` and use the resulting container image e.g. in your docker-compose stack like: 


```yaml

# nightscout services

services:
  diasend-bridge:
    image: <name-of-the-built-image> # alternatively, you can also configure a build section here if you don't have the container image readily available via e.g. docker hub
    env:
      DIASEND_USERNAME: <diasend-username>
      DIASEND_PASSWORD: <diasend-password>
      NIGHTSCOUT_URL: <url-of-nightscout-instance>
      NIGHTSCOUT_API_SECRET: <retracted>
      # ... other environment variables for configuration, see readme
```

Please let me know if that helps!
