### ISSUE TITLE
Cannot find module '/usr/local/app/dist/run.js'

### ISSUE THREAD

**Issue by AndyLow91** [burnedikt/diasend-nightscout-bridge#48]
I've followed the instructions for running this package via docker as a standalone/sidecar uploader an running into the following problem:

```
Node.js v18.15.0
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/usr/local/app/dist/run.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I'm not 100% familiar with npm but I believe there is a dependency missing?

**Steps that I followed:
copied this repo to my machine with git clone.
created a .env file with the variables required
run docker build -t diasend2nightscout . to build the image
created a docker-compose.yml file:

```
version: '3'
services:
  diasend-bridge:
    image: diasend2nightscout
    environment:
      DIASEND_USERNAME: ${DIASEND_USERNAME}
      DIASEND_PASSWORD: ${DIASEND_PASSWORD}
      NIGHTSCOUT_URL: ${NIGHTSCOUT_URL}
      NIGHTSCOUT_API_SECRET: ${NIGHTSCOUT_API_SECRET}
    restart: always
```

ran docker compose up -d.

Thanks
